### ISSUE TITLE
Lunch In and Out problem

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#3]
I was I able to ''Punch In'' in the morning but when I tried to Lunch Out and lunch In, only ''Punch Out'' box appears. When I hit the ''Punch Out'' button a dialog box appeared ''Early out?'' 
[ticket 1.docx](https://github.com/vasavah/vci-kanaka_denr-emb-ncr-testing-phase/files/4085188/ticket.1.docx)

To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fersieval0216** [comment]
Hi Ms. Honey the issue has been resolved, Kindly check on your end for confirmation. Thank you!

**Comment by Honey-ctrl** [comment]
validated
