### ISSUE TITLE
PUNCH IN, LUNCH OUT AND IN AND PUNCH OUT BUTTONS ARE MISSING (again) 

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#33]
![image](https://user-images.githubusercontent.com/60082019/81259794-46af1080-906b-11ea-97e6-aa21c276c936.png)

**Comment by pauilnapaulinapaulina** [comment]
This issue has been resolved. Kindly validate if changes are reflected on DENR EMB-NCR's Kodanda system as well. Thank you!

**Comment by Honey-ctrl** [comment]
validated

**Comment by pauilnapaulinapaulina** [comment]
This is noted. This ticket will now be closed.
