### ISSUE TITLE
REQUEST FOR FEWER BUTTON FOR IN AND OUT

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#37]
![image](https://user-images.githubusercontent.com/60082019/86073271-fde96600-bab5-11ea-9606-ce1a4e69895c.png)

May we request for the button appears in the kiosk will  be limited to : 
PUNCH IN 
LUNCH OUT 
LUNCH IN 
PUNCH OUT 

To avoid confusion with the staff, we dont practice the morning and afternoon coffee breaks here in the office. thank you

**Comment by pauilnapaulinapaulina** [comment]
Hi ms. Honey! We've implemented this request on your system. Kindly validate and confirm on your end.

**Comment by Honey-ctrl** [comment]
validated

**Comment by pauilnapaulinapaulina** [comment]
This is noted. This ticket will now be closed.
