### ISSUE TITLE
USING QUICK PUNCH

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#38]
![image](https://user-images.githubusercontent.com/60082019/86191193-4bd48d00-bafb-11ea-9931-713c2276a0ea.png)

I assigned a new pin to use the quick punch. Tried using the quick punch but screen shows NO PUNCH RECORD

**Comment by pauilnapaulinapaulina** [comment]
This issue has been resolved. Kindly validate on your end if the issue still persists.

**Comment by Honey-ctrl** [comment]
validated

**Comment by pauilnapaulinapaulina** [comment]
This is noted. This ticket will now be closed.
