### ISSUE TITLE
PUNCH IN AND OUT BUTTONS ARE MISSING 

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#39]
![image](https://user-images.githubusercontent.com/60082019/86191390-cd2c1f80-bafb-11ea-8017-6cde0f3be0d2.png)

When I first tried the system, upon log in,  there are 6 buttons appears above. Today, the buttons are missing. 

I have previously ticket the buttons be reduced into 4 buttons only (Punch In, Lunch out, Lunch in and Punch out)

**Comment by pauilnapaulinapaulina** [comment]
This issue has been resolved. Kindly validate if changes are reflected on DENR EMB-NCR's Kodanda system as well. Thank you!

**Comment by Honey-ctrl** [comment]
validated

**Comment by pauilnapaulinapaulina** [comment]
This is noted. This ticket will now be closed.
