### ISSUE TITLE
difficulty using kanaka cloud link

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#4]
Whenever I use different PC to access the kanaka.cloud link, interface showed 
[2.docx](https://github.com/vasavah/vci-kanaka_denr-emb-ncr-testing-phase/files/4114906/2.docx)

**Comment by fersieval0216** [comment]
Hi Ms. Honey, try typing po your organization name (denr-ncr) in the search box it should redirect na po sa kanaka cloud link ninyo po, please comment me back if okay na po thanks! :)

**Comment by Honey-ctrl** [comment]
ayaw pa din Sir Fers

**Comment by fersieval0216** [comment]
baka po nasama ninyo po yung parenthesis ma'am? denr-ncr lang po

**Comment by Honey-ctrl** [comment]
Sir fers tawag ka sakin pls. Thanks

**Comment by fersieval0216** [comment]
This issue has been resolved, confirmation via phone call by ms.honey
