### ISSUE TITLE
STEP 27

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#5]
For step 27, PLS CHECK LEAVE BALANCE COMPUTATION AFTER APPROVAL

An EMPLOYEE applied for January 31 to February 3 (Vacation Leave) and was approved by the APPROVER. Leave credits from previously rejected application shows 31.28 balance, upon approval of the APPROVER balance showed ''pending'' and leave balance is 30.78

**Comment by fersieval0216** [comment]
Duplicate ticket po same as DEDUCTION OF LEAVES ticket.

**Comment by fersieval0216** [comment]
Duplicate ticket po same as DEDUCTION OF LEAVES ticket.
