### ISSUE TITLE
LOGGING IN ERROR IN DIFFERENT PC

### ISSUE THREAD

**Issue by Honey-ctrl** [vasavah/vci-kanaka_denr-ncr-testing-phase#7]
I was able to log in my account in different PC (using incognito) but this dialog box appear
[ticket 3.docx](https://github.com/vasavah/vci-kanaka_denr-emb-ncr-testing-phase/files/4132655/ticket.3.docx)

**Comment by fersieval0216** [comment]
This issue has been resolved, confirmation via phone call by ms.honey
